four task
gvoz/movies pull request #4
Opened 2017-11-26 19:04 UTC by gvoz

2017-11-26 20:11 UTC, zverok requested changes

2017-11-26 20:11 UTC, zverok commented on movies.rb
> +movies = CSV.read(filename, { :col_sep => '|' }).map{ |row| OpenStruct.new(keys.zip(row).to_h) }
У CSV есть опция `headers:`, позволяющая передать заголовки колонок — так мы упростим немножко дальнейший код.
И, кстати, пример с разделителем колонок в доках в устаревшем синтаксисе:
а) словари с ключами-символами можно писать вот так: `col_sep: '|'`
б) когда словарь — последний аргумент метода, скобки не нужны, руби и так поймёт: `CSV.read(filename, col_sep: '|', headers: ...)`

2017-11-26 20:11 UTC, zverok commented on movies.rb
> +puts_movies(movies.select{ |movie| movie.genres.include?('Comedy') }.sort_by{ |movie| movie.date.to_i}.first(10) )
Кстати, пропустил в прошлом уроке: сортировка по `to_i` некорректна (можно проверить — для всех фильмов одного года порядок будет случайный), можно просто по строковому значению же.

2017-11-26 20:11 UTC, zverok commented on movies.rb
> +movies.map{ |movie| movie.director }.uniq.sort_by{ |a| a.split.last }.each{ |a| puts a }
Маленький трюк: для таких простых блоков (только один метод без аргументов) есть сокращённый синтаксис: `map(&:director)` (гуглить `Symbol#to_proc`)

2017-11-26 20:11 UTC, zverok commented on movies.rb
> +dates = movies.map{ |movie| Date.strptime(movie.date, '%Y-%m').month if movie.date.size > 4 }.compact
if + compact тяжело читаются (не сразу понятно, что имелось в виду), лучше reject + map

2017-11-26 20:11 UTC, zverok commented on movies.rb
> +dates.uniq.sort.map{|month| [Date::MONTHNAMES[month], dates.count(month)]}.each{ |a| puts "#{a[0]}: #{a[1]}"}
`dates.count(...)` для каждого месяца очень неоптимально (чтобы посчитать кол-во, он 12 раз проходит по одному и тому же массиву), лучше `group_by` или `each_with_object` с хешом.

2017-11-26 21:50 UTC, gvoz commented on movies.rb
> +puts_movies(movies.select{ |movie| movie.genres.include?('Comedy') }.sort_by{ |movie| movie.date.to_i}.first(10) )
to_i перенеслось из сортировки по длительности, а в выборке года были разные вот и не заметил ошибку.

2017-11-27 07:34 UTC, zverok approved these changes

2017-11-27 07:34 UTC, zverok commented on movies.rb
> +movies.reject{ |movie| movie.date.size < 6}.map{ |movie| Date.strptime(movie.date, '%Y-%m').month }.sort.group_by{ |e| e }.each{ |k, v| puts "#{Date::MONTHNAMES[k]}: #{v.size}"}
Идиома group by itself (`group_by { |e| e }`) в Руби, как ни смешно, так и записывается: `group_by(&:itself)` (никакой магии, просто у любого объекта есть метод `itself`, возвращающий этот же объект).

2017-11-27 11:59 UTC, merged